import {
  MdDashboard,
  MdFlashOn,
  MdVisibility,
  MdAccessTime,
  MdArchive,
  MdArticle,
  MdAirplay,
  // MdSchool,
  // MdExplore,
  // MdAdd,
  // MdCheckCircle,
  // MdLibraryBooks,
  // MdBookmark,
  // MdHighlight,
  // MdCloudUpload,
  MdPerson,
  // MdAssessment,
  // MdQuiz,
  // MdFlag,
  // MdTune,
  MdBarChart,
  MdTrendingUp,
  MdTrackChanges,
  // MdReport,
  // MdEmojiEvents,
  // MdAndroid,
  // MdChat,
  // MdSchedule,
  // MdHelp,
  // MdRecommend,
} from 'react-icons/md';
import { SidebarConfig } from './Sidebar';

const menuItems: SidebarConfig = {
  logo: {
    src: '/logo.png',
    alt: 'HireMind Logo',
    title: 'HireMind',
  },
  showProfile: false,
  showLogout: false,
  menuItems: [
    {
      id: 'dashboard',
      name: 'Dashboard',
      icon: <MdDashboard />,
      type: 'heading',
      children: [
        {
          id: 'overview',
          name: 'Overview',
          icon: <MdVisibility />,
          href: '/dashboard',
          type: 'link',
        },
        // {
        //   id: 'quick-actions',
        //   name: 'Quick Actions',
        //   icon: <MdFlashOn />,
        //   href: '/dashboard/quick-actions',
        //   type: 'link',
        // },
      ],
    },
    {
      id: 'analytics',
      name: 'Analytics',
      icon: <MdBarChart />,
      type: 'heading',
      children: [
        {
          id: 'learning-dashboard',
          name: 'Learning Dashboard',
          icon: <MdDashboard />,
          href: '/dashboard/learning-dashboard',
          type: 'link',
        },
        {
          id: 'skill-progress',
          name: 'Skill Progress',
          icon: <MdTrendingUp />,
          href: '/dashboard/skill-progress',
          type: 'link',
        },
        {
          id: 'goal-tracking',
          name: 'Goal Tracking',
          icon: <MdTrackChanges />,
          href: '/dashboard/goal-tracking',
          type: 'link',
        },
        // {
        // 	id: "performance-reports",
        // 	name: "Performance Reports",
        // 	icon: <MdReport />,
        // 	href: "/dashboard/performance-reports",
        // 	type: "link",
        // },
        // {
        // 	id: "achievements",
        // 	name: "Achievements",
        // 	icon: <MdEmojiEvents />,
        // 	href: "/dashboard/achievements",
        // 	type: "link",
        // },
      ],
    },
    {
      id: 'interview',
      name: 'Interview',
      icon: <MdAirplay />,
      type: 'heading',
      children: [
        {
          id: 'schedule-interview',
          name: 'Schedule Interview',
          icon: <MdAccessTime />,
          href: '/dashboard/interview/schedule',
          type: 'link',
        },
        {
          id: 'interview-results',
          name: 'Interview Results',
          icon: <MdArchive />,
          href: '/dashboard/interview/result',
          type: 'link',
        },
        {
          id: 'practice-questions',
          name: 'Practice Questions',
          icon: <MdArticle />,
          href: '/dashboard/interview/prepare',
          type: 'link',
        },
      ],
    },
    // {
    //   id: 'ai-mentor',
    //   name: 'AI Mentor',
    //   icon: <MdAndroid />,
    //   type: 'heading',
    //   children: [
    //     {
    //       id: 'chat-mentor',
    //       name: 'Chat with Mentor',
    //       icon: <MdChat />,
    //       href: '/dashboard/ai-chat',
    //       type: 'link',
    //     },
    //     {
    //       id: 'study-planner',
    //       name: 'Study Planner',
    //       icon: <MdSchedule />,
    //       href: '/dashboard/study-planner',
    //       type: 'link',
    //     },
    //     {
    //       id: 'ask-questions',
    //       name: 'Ask Questions',
    //       icon: <MdHelp />,
    //       href: '/dashboard/ask-questions',
    //       type: 'link',
    //     },
    //     {
    //       id: 'get-recommendations',
    //       name: 'Get Recommendations',
    //       icon: <MdRecommend />,
    //       href: '/dashboard/recommendations',
    //       type: 'link',
    //     },
    //   ],
    // },
    // {
    //   id: 'learning-paths',
    //   name: 'Learning Paths',
    //   icon: <MdSchool />,
    //   type: 'heading',
    //   children: [
    //     {
    //       id: 'my-paths',
    //       name: 'My Paths',
    //       icon: <MdPerson />,
    //       href: '/dashboard/my-paths',
    //       type: 'link',
    //     },
    //     {
    //       id: 'browse-paths',
    //       name: 'Browse All Paths',
    //       icon: <MdExplore />,
    //       href: '/dashboard/browse-paths',
    //       type: 'link',
    //     },
    //     {
    //       id: 'create-path',
    //       name: 'Create Custom Path',
    //       icon: <MdAdd />,
    //       href: '/dashboard/create-path',
    //       type: 'link',
    //     },
    //     {
    //       id: 'completed-paths',
    //       name: 'Completed Paths',
    //       icon: <MdCheckCircle />,
    //       href: '/dashboard/completed-paths',
    //       type: 'link',
    //       badge: 'New',
    //     },
    //   ],
    // },
    {
      id: 'resume-builder',
      name: 'Resume Builder',
      icon: <MdFlashOn />,
      type: 'heading',
      children: [
        {
          id: 'builder',
          name: 'Open Builder',
          icon: <MdPerson />,
          href: '/resume',
          type: 'link',
        },
      ],
    },
    // {
    //   id: 'resources',
    //   name: 'Resources',
    //   icon: <MdBook />,
    //   type: 'heading',
    //   children: [
    //     {
    //       id: 'my-library',
    //       name: 'My Library',
    //       icon: <MdLibraryBooks />,
    //       href: '/dashboard/library',
    //       type: 'link',
    //     },
    //     {
    //       id: 'bookmarks',
    //       name: 'Bookmarks',
    //       icon: <MdBookmark />,
    //       href: '/dashboard/bookmarks',
    //       type: 'link',
    //     },
    //     {
    //       id: 'notes-highlights',
    //       name: 'Notes & Highlights',
    //       icon: <MdHighlight />,
    //       href: '/dashboard/notes',
    //       type: 'link',
    //     },
    //     {
    //       id: 'browse-resources',
    //       name: 'Browse Resources',
    //       icon: <MdExplore />,
    //       href: '/dashboard/browse-resources',
    //       type: 'link',
    //     },
    //     {
    //       id: 'upload-content',
    //       name: 'Upload Content',
    //       icon: <MdCloudUpload />,
    //       href: '/dashboard/upload',
    //       type: 'link',
    //     },
    //   ],
    // },
    // {
    // 	id: "profile-assessment",
    // 	name: "Profile & Assessment",
    // 	icon: <MdPerson />,
    // 	type: "heading",
    // 	children: [
    // 		{
    // 			id: "personal-profile",
    // 			name: "Personal Profile",
    // 			icon: <MdPerson />,
    // 			href: "/dashboard/profile",
    // 			type: "link",
    // 		},
    // 		{
    // 			id: "skills-assessment",
    // 			name: "Skills Assessment",
    // 			icon: <MdAssessment />,
    // 			href: "/dashboard/skills-assessment",
    // 			type: "link",
    // 		},
    // 		{
    // 			id: "interest-survey",
    // 			name: "Interest Survey",
    // 			icon: <MdQuiz />,
    // 			href: "/dashboard/interest-survey",
    // 			type: "link",
    // 		},
    // 		{
    // 			id: "career-goals",
    // 			name: "Career Goals",
    // 			icon: <MdFlag />,
    // 			href: "/dashboard/career-goals",
    // 			type: "link",
    // 		},
    // 		{
    // 			id: "learning-preferences",
    // 			name: "Learning Preferences",
    // 			icon: <MdTune />,
    // 			href: "/dashboard/learning-preferences",
    // 			type: "link",
    // 		},
    // 	],
    // },
  ],
};

export default menuItems;
